name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Build ASP.NET project
      run: |
        dotnet build -c Release

    - name: Publish ASP.NET project
      run: |
        dotnet publish -c Release -o out

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/tech-hub-server:latest .
        docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/tech-hub-server:latest
