// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
namespace DefaultSuite
{
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Signin() {
    driver.Navigate().GoToUrl("http://localhost:8080/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 832);
    driver.FindElement(By.CssSelector(".slick-current:nth-child(6) a")).Click();
    driver.FindElement(By.CssSelector("#tab1 .product:nth-child(6) .add-to-compare")).Click();
    driver.FindElement(By.CssSelector(".add-to-cart-btn:nth-child(2)")).Click();
    driver.FindElement(By.LinkText("MAC BOOK PRO")).Click();
    driver.FindElement(By.CssSelector(".section:nth-child(5)")).Click();
    driver.FindElement(By.LinkText("Details")).Click();
    driver.FindElement(By.LinkText("Reviews (2)")).Click();
    driver.FindElement(By.CssSelector("label:nth-child(4)")).Click();
    driver.FindElement(By.Id("namme")).Click();
    driver.FindElement(By.Id("namme")).SendKeys("knkjnkj");
    driver.FindElement(By.Id("emaiil")).Click();
    driver.FindElement(By.Id("emaiil")).SendKeys("faresshohdy0@gmail.com");
    driver.FindElement(By.Id("revieew")).Click();
    driver.FindElement(By.Id("revieew")).SendKeys("nkjnkjnkjn");
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.CssSelector(".col-md-3:nth-child(4) li:nth-child(1) > a")).Click();
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.Id("fullName")).Click();
    driver.FindElement(By.Id("fullName")).SendKeys("faris muhammad shohdy tawfeek sharara");
    driver.FindElement(By.Id("eMail")).SendKeys("faresshohdy0@gmail.com");
    driver.FindElement(By.Id("phone")).SendKeys("01005593348");
    driver.FindElement(By.Id("Street")).SendKeys("10 zeifal st. muharam beh");
    driver.FindElement(By.Id("ciTy")).SendKeys("alexandria ");
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.CssSelector("div:nth-child(1) > a > span")).Click();
    driver.FindElement(By.CssSelector(".signin-image")).Click();
    driver.FindElement(By.LinkText("Create an account")).Click();
    driver.FindElement(By.CssSelector(".dropdown-toggle > span")).Click();
    driver.FindElement(By.LinkText("View Cart")).Click();
    driver.FindElement(By.LinkText("View Cart")).Click();
    driver.FindElement(By.LinkText("Checkout")).Click();
    driver.FindElement(By.CssSelector(".input-radio:nth-child(1) > label")).Click();
    driver.FindElement(By.CssSelector(".input-radio:nth-child(2) span")).Click();
    driver.FindElement(By.Name("first-name")).Click();
    driver.FindElement(By.Name("first-name")).SendKeys("faris");
    driver.FindElement(By.Name("last-name")).SendKeys("sharara");
    driver.FindElement(By.Name("email")).SendKeys("faresshohdy0@gmail.com");
    driver.FindElement(By.Name("address")).SendKeys("10 zeifal st. muharam beh");
    driver.FindElement(By.Name("city")).SendKeys("alexandria ");
    driver.FindElement(By.Name("country")).SendKeys("Egypt");
    driver.FindElement(By.Name("tel")).SendKeys("01005593348");
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.CssSelector(".primary-btn")).Click();
    driver.FindElement(By.CssSelector("h1")).Click();
    driver.FindElement(By.CssSelector(".dropdown-toggle > span")).Click();
    driver.FindElement(By.LinkText("View Cart")).Click();
  }
}
}